### PR TITLE
Add support for CHANGE_NOTIFICATIONS_MIN_INTERVAL

### PR DESCRIPTION
**Pull request by smortex**
When CHANGE_NOTIFICATIONS_MIN_INTERVAL is in use, a crontab must be setup.

### CODE REVIEW

**Comment by neomilium** [comment]
Still a draft?

**Review by neomilium — APPROVED** [review]

**Comment by smortex** [comment]
Hehe, yes, I am confused :clown_face: … I don't recall receiving such e-mail, but when running this cron job I was not flooded by notifications so I am not sure about what to think…

I probably should try to create another user account and send notifications from one account to the other to confirm whether this is required or not…

**Comment by neomilium** [comment]
In main description, you are talking about due dates and now about sending notifications from a user to another… you confused me too ;-)

Without cron job, email notifications are already sent, so what? cron job is only for due dates, right?

**Comment by smortex** [comment]
Yeah, confusion is total…  sorry.

Since we are not using celery, mail are [supposed to be] send synchronously.  I guess they are because if they where not we would already have been checking what was going on.

But I could not find anything related to expiration dates…  which makes sense since I would not expect them to be send after an HTTP request.

https://github.com/taigaio/taiga-back/issues/894 and https://github.com/taigaio/taiga-back/issues/1251 give some details about the way notifications are supposed to work and how the documentation is lacking in this area.  The fact that after running the cron job I did not receive notification about expired events is the reason of my confusion.  I need to take the time to check more carefully.

**Comment by smortex** [comment]
Okay, my setup has a misconfiguration that prevents the mails from being sent.

So, regarding this PR, if we trust https://github.com/taigaio/taiga-back/issues/1309, then for now we can choose one of:

1. Keep everything as-is, do not set `CHANGE_NOTIFICATIONS_MIN_INTERVAL`, do not use a crontab, and email are send synchronously when events occur.  If at some point some code is added to send notifications when due dates are arriving / past it will likely not work;
2. Set `CHANGE_NOTIFICATIONS_MIN_INTERVAL` to some value and setup a crontab to send at most 1 mail every `CHANGE_NOTIFICATIONS_MIN_INTERVAL` per modified task.

I really do not care much at this point.  What do you think @neomilium?

**Comment by neomilium** [comment]
As we are now using due dates, our setup works as expected, if you use due dates, it seems that only second solution will work.

Like you, I don't care about this feature…

**Comment by smortex** [comment]
So after understanding what we can expect and what we cannot expect, I reworked the whole PR to add a new parameter to setup notification minimum interval and manage the cron job depending on the setting.

**Review by neomilium — APPROVED** [review]

**Pull request merged**
